### ISSUE TITLE
[ERROR] (node:521) UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by ygx0** [Cyw00d/MMM-Bluelinky#1]
[03.03.2021 07:12.26.981] [ERROR] (node:521) UnhandledPromiseRejectionWarning: RequestError: write EPROTO 3065799888:error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small:../deps/openssl/openssl/ssl/statem/statem_clnt.c:2159:

    at ClientRequest.request.once.error (/home/pi/MagicMirror/modules/MMM-Bluelinky/node_modules/got/source/request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:203:15)
    at ClientRequest.origin.emit.args (/home/pi/MagicMirror/modules/MMM-Bluelinky/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:198:13)
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:436:5)
    at onwrite (_stream_writable.js:461:5)
    at _destroy (internal/streams/destroy.js:49:7)
    at TLSSocket.Socket._destroy (net.js:613:3)
    at TLSSocket.destroy (internal/streams/destroy.js:37:8)
    at WriteWrap.afterWrite [as oncomplete] (net.js:790:10)
[03.03.2021 07:12.27.129] [ERROR] (node:521) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

**Comment by ygx0** [comment]
@Cyw00d @stolktech any idea why this is happening or how to fix it?

**Comment by ygx0** [comment]
Changed /etc/ssl/openssl.cnf according to a StackExchand post:

CipherString = DEFAULT:@SECLEVEL=2  
to
CipherString = DEFAULT:@SECLEVEL=1

but still no luck.

**Comment by Hacksore** [comment]
Might be worth updating bluelinky to see if this fixes this issue? 

edit: created #2 and we can see if that helps

**Comment by ygx0** [comment]
@Hacksore you were right, I had bluelinky 5.2.2 which is the one in the dependencies, manually updating it to 6.0.1 solved the issue.

**Comment by ghost** [comment]
The PR from Hacksore has been merged, thanks for contributing!
Let me know when anything else needs to be updated.
